{% set name = "WSGIProxy2" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: caa8958b5b3cc908c60fc2b801c9779da2036e9f1f44828e966e0b24d46ea9a5

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - webob
    - six

test:
  imports:
    - wsgiproxy

about:
  home: https://github.com/gawel/WSGIProxy2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A WSGI Proxy with various http client backends
  doc_url: https://wsgiproxy2.readthedocs.org
  dev_url: https://github.com/gawel/WSGIProxy2

extra:
  recipe-maintainers:
    - nehaljwani
