{% set version = "0.4.5" %}

package:
  name: wsgiproxy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/W/WSGIProxy2/WSGIProxy2-{{ version }}.tar.gz
  sha256: caa8958b5b3cc908c60fc2b801c9779da2036e9f1f44828e966e0b24d46ea9a5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - webob
    - six

test:
  imports:
    - wsgiproxy

about:
  home: https://github.com/gawel/WSGIProxy2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A WSGI Proxy with various http client backends
  doc_url: https://wsgiproxy2.readthedocs.org
  dev_url: https://github.com/gawel/WSGIProxy2

extra:
  recipe-maintainers:
    - nehaljwani
