travis:
  secure:
    BINSTAR_TOKEN: NxO6bEAbrfJLhpuhFjZ5X7njS/onQFTVQeCNzEdaqOY+TrOrwY3AjwdRnMp2W1MYHuO9X/jKdfwP+SvD1gXyXFFtUqGMZyWr2TFBd0yGLpgnEbd7jp+p+Ba/tRIRu8hatGFQP0TkvBkZgBNBKBaOpNMrxEQMipRnISipdUyevHRcTXNPYhpPUCCBX0uB2k8ZDOTorCEqj/2ZomFWxypFURG80zWB8iaOflWcNqaMqBfvSciz2ebp04OUOYmBCSdp0pjjBddJuNQfBUGswneX1xFIyZkfAGH/l6yClC8pPi5nlg7ARhXxYTwJcQUNjnjB3BQdhNRnjXj7g40LbyLOOKjWjq+xiyHPe0XTkrby11cDgHcbnNJuYPxeFCpFLbqeVPotGv5k1+MxTj0pyUClqGAFCgm66/3mcwOC/L4pECFVJeyjZ2LOza5gDSdpXwmYtcnhzzQWSX51e9b5e+yXHfgMnWjNomS711FWGtpsilDr8KEz8MSXD1jqoa35wSrrvnfDMWjCDT1YZTHE+xh1dvrDMnZ3Y9pbkFtsQZUZXqVfKRKXrBm51EayExUMLdPzOdi84QiMrU+L7unyMnzNd+PTg0PyisIFrKE9KtY6m0qf4+bk1P8kiIRkSTVO64AqzIqeDm81IuxnOQhutPoTtl+7UP4i0Luqz+k61SU+Bbo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
