travis:
  secure:
    BINSTAR_TOKEN: GpfeYq7aJmzi26+N7YYNpg+pudroTCfhiQfJhCKBnXQ9P2x0TSEOCIIeP5cF5KBGbpfJl8bYIO1muDeTvEd53l3WKIscX7sjw6b3qQJTl2kkis2XOaunMLACyUE2ez6LnaSexaAnZdUNjlhrxzcHRVaux1dIrSM6rg3wAZYrx6wcSG6+o1KWjGVFiMXEcqN4rKW1Mbz86nmz0J6bflTP7Xr4a2GyDP9/PFujGZRaLq3mDuB1Ism+ExnLd8DW0+ybTbgjALmi+JbwGHYhwU97NMuK7xr5bYHk+xtw27yNDNSVYm9qmv/53HM0XeGLFL4Ha4NiUh+yJyCpX8z68rP5+pMGAFP+0RsBz7ibBBfMjgo5fyJshUhNiux17NbTTWJP1MLx0yw5FWUG8iuugzuT7oHput3OQsSCKvvEGKVJ+QH6B1tqWt6298Vruw9QDEiBMMV7yP+lW6rUzAysqB/iqtKu0m29MKHmCyFVsJNUisegC453AiPXJ1LIFJuiRYByHSJ6+r9g2EK7DgkYUaJo/QFbWWFR8A9SJfXOKFpavYU1sujhLIcikdI0pzaAiZUQlyEVXU6lcb3DmmhzRY2x1Lxp9KW1BzZCf+vKY4Gg6o5jvNFn801iAaE5dFqd/k0q/qpecx7Jnaxxp4QUkjHp/jdIB1da1VIn1zpNlmGnkUY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
